GNU nano 4.8                                                                                                                                                                           
version: '3.8'
volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: bdcry/yamdb_final:latest
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
