version: '3.8'
volumes:
  postgres_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: wadimegoroff/foodgram-project:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/host.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
      - media_data:/var/html/media/